Cargo.toml

Update dependencies. Notably:
- update embedded-hal to 1.0.0, which is what will be developed against
- use version of stm32h5 available on crates.io (0.15.1)
- Add `defmt` as an optional dependency, to be used later
- Add `paste`, to be used in subsequent PRs

deps: Update dependencies

---

src/prelude.rs

embedded-hal 1.0 does not have a prelude to import (0.27 did).

prelude: Remove import of embedded-hal prelude

---

src/lib.rs
src/time.rs

Preparation for the RCC module, which is also based on the RCC module from stm32h7xx-hal.

time: Add time module from stm32h7xx-hal

---

Cargo.toml
src/time.rs

Clippy added new lint errors with Rust 1.80 apparently, so fix them.

clippy: fix new lint errors with 1.80

---

src/rcc.rs
src/rcc/core_clocks.rs

This adds the CoreClocks struct definition and associated helper functions to get clocks. 
At this time it only defines the clocks present on the STM32H503

rcc: Add core clocks definitions

---

src/rcc.rs
src/rcc/rec.rs

Adds helper functions for enabling, resetting and disabling peripherals via the RCC control interface.
Note: This also disables builds for the STM32H56/7x processors as the STM32H5 PAC crate does not provide the necessary definitions for the RCC at this time.

rcc: Add peripheral reset and control

---

src/prelude.rs
src/rcc.rs
src/rcc/pll.rs
src/rcc/rec.rs

This implements the PLL and clock configuration logic for the processor using the RCC peripheral. 
- The `pll` module is responsible for configuring the VCOs and setting up the PLL dividers for the desired frequency
- The `freeze` method in the `rcc` module does the heavy lifting for making sure that the processor clocks are configured in the desired manner
Note: This is largely copied from the implementation in stm32h7xx-hal, although it significantly refactors and modifies the PLL configuration in the `pll` module. This was mostly due to the differences in the register definitions used by the calculation and the fact that the H5 family (and especially the H503 MCU) is quite a bit simpler than the H7 family. I made significant changes to the the PLL configuration due to the stm32h7xx-hal …

rcc: Calculate PLL clocks and implement core clock configuration logic

---

src/rcc.rs
src/rcc/mco.rs

Add the MCO configuration in the `mco` module and configure MCOs appropriately during RCC `freeze` operation.

rcc: Add MCO configuration

---

Cargo.toml
examples/blinky.rs
examples/fractional-pll.rs
examples/rcc.rs

This adds 2 examples demonstrating RCC configuration. It also updates the blinky example to use the RCC to set up the MCU for 250MHz operation

examples: Add rcc and fractional-pll examples

---

Cargo.toml
src/gpio.rs
src/gpio/gpio_def.rs
src/lib.rs
src/prelude.rs

This adds the basic outline functionality for the GPIO module and will form the base for follow-up PRs (see #19, #20, #21)  to round out the GPIO functionality. 
The gpio module is largely based on/copied from the implementation in [stm32h7xx-hal](https://github.com/stm32-rs/stm32h7xx-hal).

gpio: Add basic functionality for GPIOs

---

src/gpio.rs
src/gpio/erased.rs
src/gpio/gpio_def.rs
src/gpio/partially_erased.rs

Add pin type erasure so that pins can be used interchangeably as the same type. Pin port and number are stored in the struct instead of being encoded in the type.
This is taken directly from the implementation in [stm32h7xx-hal](https://github.com/stm32-rs/stm32h7xx-hal).

gpio: add ErasedPin and PartiallyErasedPin

---

src/icache.rs
src/lib.rs
src/prelude.rs

Add management functions for the ICACHE instruction cache peripheral.

icache: Add ICACHE management

---

tools/verify-rust-version.js

The Version check script started failing on master, but it was also crashing on exit, losing the error message. This fixes the exit code, in the way described in the Node.js documentation [here](https://nodejs.org/api/process.html#processexitcode)

Fix version check script

---

src/gpio.rs
src/gpio/convert.rs
src/gpio/dynamic.rs
src/lib.rs

- Add DynamicPin to allow for dynamic pin mode changes
- Add type conversion functions for pin configuration
This is taken directly from the implementation in [stm32h7xx-hal](https://github.com/stm32-rs/stm32h7xx-hal).

gpio: add dynamic pin support and conversion functions

---

examples/blinky.rs
src/delay.rs
src/lib.rs
src/prelude.rs

This implements the embedded-hal 1.0 `DelayNs` trait. The cortex-m crate has essentially the same logic, but the published version is based on embedded-hal 0.2. This can be removed (repurposed for use with timers?) when a new version of the cortex-m crate is published.
The blinky example has been updated to use the delay module.

delay: Add delay module

---

Cargo.toml
examples/blinky.rs

Use the recently completed GPIO driver in the blinky example

examples: update blinky example to use GPIO driver

---

Cargo.toml
src/gpio/gpio_def.rs
src/rcc/rec.rs

Add Peripheral clock + reset/enable definitions for the rest of the H5 family (for which we have SVDs - still waiting on the H523/H533 SVDs).

rcc: add peripheral clock definitions for the rest of the H5 family

---

src/gpio.rs
src/gpio/hal.rs

This adds the implementation of the embedded-hal traits for the various GPIO struct definitions.

gpio: Add embedded-hal implementation

---

examples/spi.rs
src/spi.rs
src/spi/hal.rs

Note: this targets the stm32h5xx-hal:as/spi-master branch

Spi master - Add support for H523,533,56x and 573

---

examples/fractional-pll.rs
src/rcc.rs
src/rcc/core_clocks.rs
src/rcc/pll.rs

The STM32H523/STM32H533/STM32H56x/STM32H573 parts have a 3rd PLL. This configures them the same way PLL2 is configured. 
Caveat: I haven't tested configuration of PLL3 on one of the above parts as I don't have any.

rcc: configure PLL3 for the rest of the H5 family

---

Cargo.toml
examples/i2c.rs
src/i2c.rs
src/i2c/hal.rs
src/i2c/i2c_def.rs
src/lib.rs
src/macros.rs
src/prelude.rs

This adds the I2C Controller driver implementation for the STM32H5. It implements a blocking, and non-blocking API, as well as the embedded-hal 1.0 traits.
It borrows a lot from the STM32H7 HAL (particularly the TIMINGR configuration, which is a bit inscrutable in the reference manual), but it borrows the `Instance` concept from the STM32F4 project to minimize the need for macros. 
It uses the updated terminology of Controller/Target from the latest version of the I2C spec (Rev. 7.0)

i2c: Add I2C Controller implementation

---

src/gpio.rs

Found out that the offset for setting the pull up/down resistor is wrong during #52

Fix bad offsets

---

README.md

Trying to improve the landing README to better reflect the current state of the project.

Update README with up to date information about product/peripheral support

---

examples/spi.rs
examples/spi_send_frames.rs
src/lib.rs
src/prelude.rs
src/spi.rs
src/spi/config.rs
src/spi/hal.rs
src/spi/nonblocking.rs
src/spi/spi_def.rs
src/spi/transaction.rs

This adds a master mode implementation for the SPI peripheral. 
The driver is split such that the core logic is implemented in spi.rs, and the rest is contained within a submodule:
- User configuration is split off into the config module
- The transaction module encapsulates the different transaction types (read, write, transfer, transfer inplace). Buffer management is abstracted into the transaction type to enable non-blocking usage the peripheral.
- The public facing APIs are mostly implemented in the hal module (embedded-hal trait implementations), and the nonblocking module, which exposes a NonBlocking trait that a user needs to explicitly use in order to use the non-blocking APIs (expected to be the less used case, this avoids polluting the public API too much).

spi: Add SPI master implementation

---

examples/dwt-blinky.rs
src/dwt.rs
src/lib.rs
src/prelude.rs

The DWT unit allows cycle count based profiling/tracing for performance testing. The [module in the
stm32f4xx-hal](https://github.com/stm32-rs/stm32f4xx-hal/blob/master/src/dwt.rs) is a useful tool for managing this functionality, so I'm copying it verbatim (with very minor changes for imports) here.

dwt: copy DWT management and profiling features from stm32f4xx-hal (#50)

---

Cargo.toml
src/gpdma.rs
src/gpdma/ch.rs
src/gpdma/future.rs

This implements futures for GPDMA transfers by adding a wrapper for `DmaTransfer`, `DmaTransferFuture`, implementing Future for `DmaTransferFuture` in the `gpdma::future` module, which is created when a `DmaTransfer` is awaited via the `IntoFuture` trait. Under the hood, the implementation uses an `AtomicWaker` from the [`futures-util`](https://docs.rs/futures-util/latest/futures_util/) crate and channel interrupts to drive the future. Because the wakers need to be defined statically in order to be accessible from the channel interrupts, and to prevent accidental colliding implementations of interrupt handlers for the DMA channels, the futures implementation is hidden behind the `gpdma-future` feature flag.

DMA Futures

---

.vscode/settings.json
Cross.toml
README.md

This allows running unit tests on a non-linux platform via the `cross test` command.

Add cross configuration
